sudo: required
services:
    - docker

before_install:
    - docker build -t vincegnzls/react-docker-practice -f Dockerfile.dev .

script:
    - docker run -e CI=true vincegnzls/react-docker-practice npm run test