version: '3'

services: 
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        image: web_react_app
        ports:
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - .:/app
        tty: true

    test:
        build:
            context: .
            dockerfile: Dockerfile.dev
        image: test_react_app
        volumes:
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]
        tty: true